
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.urjc.master.semv.cup;

import java_cup.runtime.Symbol;
import com.urjc.master.semv.types.Type;
import com.urjc.master.semv.ambito.Ambito;
import com.urjc.master.semv.commands.Command;
import com.urjc.master.semv.commands.Function;
import com.urjc.master.semv.commands.Variable;
import com.urjc.master.semv.enums.EnumType;
import com.urjc.master.semv.list.Lid;
import com.urjc.master.semv.list.ListParams;
import com.urjc.master.semv.types.TupleTypes;
import com.urjc.master.semv.includes.File;
import com.urjc.master.semv.includes.Include;
import com.urjc.master.semv.commands.Parametro;
import com.urjc.master.semv.operadores.Operador;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\104\000\002\004\005\000\002\002\004\000\002\004" +
    "\004\000\002\004\004\000\002\004\003\000\002\002\004" +
    "\000\002\002\003\000\002\003\005\000\002\005\004\000" +
    "\002\026\002\000\002\017\010\000\002\027\002\000\002" +
    "\017\010\000\002\016\006\000\002\016\004\000\002\016" +
    "\002\000\002\006\005\000\002\007\004\000\002\007\003" +
    "\000\002\030\002\000\002\010\006\000\002\010\006\000" +
    "\002\010\007\000\002\010\005\000\002\031\002\000\002" +
    "\010\012\000\002\032\002\000\002\025\005\000\002\025" +
    "\002\000\002\033\002\000\002\010\020\000\002\034\002" +
    "\000\002\010\010\000\002\035\002\000\002\010\011\000" +
    "\002\036\002\000\002\010\004\000\002\010\003\000\002" +
    "\015\003\000\002\015\005\000\002\015\002\000\002\011" +
    "\005\000\002\011\005\000\002\011\003\000\002\012\005" +
    "\000\002\012\005\000\002\012\003\000\002\013\006\000" +
    "\002\037\002\000\002\013\006\000\002\013\003\000\002" +
    "\013\003\000\002\013\003\000\002\014\003\000\002\014" +
    "\003\000\002\014\003\000\002\020\005\000\002\020\003" +
    "\000\002\021\005\000\002\021\003\000\002\022\003\000" +
    "\002\022\004\000\002\023\005\000\002\024\003\000\002" +
    "\024\003\000\002\024\003\000\002\024\003\000\002\024" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\206\000\012\041\006\045\011\046\010\047\014\001" +
    "\002\000\004\002\210\001\002\000\014\002\ufffd\041\006" +
    "\045\011\046\010\047\014\001\002\000\004\042\205\001" +
    "\002\000\012\041\006\045\ufffb\046\ufffb\047\ufffb\001\002" +
    "\000\006\014\uffcb\050\uffcb\001\002\000\006\014\uffcc\050" +
    "\uffcc\001\002\000\004\050\020\001\002\000\010\045\011" +
    "\046\010\047\014\001\002\000\006\014\uffca\050\uffca\001" +
    "\002\000\014\002\uffff\041\006\045\011\046\010\047\014" +
    "\001\002\000\004\002\001\001\002\000\014\002\ufff9\041" +
    "\ufff9\045\ufff9\046\ufff9\047\ufff9\001\002\000\004\005\021" +
    "\001\002\000\014\006\ufff2\013\ufff2\045\023\046\010\047" +
    "\014\001\002\000\006\006\ufff8\013\176\001\002\000\006" +
    "\006\ufff6\050\uffcc\001\002\000\004\050\025\001\002\000" +
    "\006\006\ufff3\013\ufff3\001\002\000\004\006\027\001\002" +
    "\000\004\007\030\001\002\000\030\004\042\007\uffde\014" +
    "\035\022\032\025\033\026\043\027\041\045\011\046\010" +
    "\047\014\050\034\001\002\000\014\002\ufff5\041\ufff5\045" +
    "\ufff5\046\ufff5\047\ufff5\001\002\000\004\005\164\001\002" +
    "\000\004\005\147\001\002\000\006\005\141\015\140\001" +
    "\002\000\032\004\uffdc\007\uffdc\010\uffdc\014\uffdc\022\uffdc" +
    "\025\uffdc\026\uffdc\027\uffdc\045\uffdc\046\uffdc\047\uffdc\050" +
    "\uffdc\001\002\000\032\004\042\007\uffde\010\137\014\035" +
    "\022\032\025\033\026\043\027\041\045\011\046\010\047" +
    "\014\050\034\001\002\000\032\004\uffef\007\uffef\010\uffef" +
    "\014\uffef\022\uffef\025\uffef\026\uffef\027\uffef\045\uffef\046" +
    "\uffef\047\uffef\050\uffef\001\002\000\006\014\uffd9\050\117" +
    "\001\002\000\004\007\uffe0\001\002\000\012\011\057\043" +
    "\052\044\047\050\051\001\002\000\004\005\046\001\002" +
    "\000\004\007\030\001\002\000\032\004\uffdd\007\uffdd\010" +
    "\uffdd\014\uffdd\022\uffdd\025\uffdd\026\uffdd\027\uffdd\045\uffdd" +
    "\046\uffdd\047\uffdd\050\uffdd\001\002\000\014\011\057\031" +
    "\061\043\052\044\047\050\051\001\002\000\036\006\uffcd" +
    "\012\uffcd\014\uffcd\016\uffcd\017\uffcd\020\uffcd\021\uffcd\032" +
    "\uffcd\033\uffcd\034\uffcd\035\uffcd\036\uffcd\037\uffcd\040\uffcd" +
    "\001\002\000\012\006\uffc6\014\uffc6\032\uffc6\033\uffc6\001" +
    "\002\000\040\005\115\006\uffcf\012\uffcf\014\uffcf\016\uffcf" +
    "\017\uffcf\020\uffcf\021\uffcf\032\uffcf\033\uffcf\034\uffcf\035" +
    "\uffcf\036\uffcf\037\uffcf\040\uffcf\001\002\000\036\006\uffce" +
    "\012\uffce\014\uffce\016\uffce\017\uffce\020\uffce\021\uffce\032" +
    "\uffce\033\uffce\034\uffce\035\uffce\036\uffce\037\uffce\040\uffce" +
    "\001\002\000\036\006\uffd3\012\uffd3\014\uffd3\016\uffd3\017" +
    "\uffd3\020\uffd3\021\uffd3\032\uffd3\033\uffd3\034\uffd3\035\uffd3" +
    "\036\uffd3\037\uffd3\040\uffd3\001\002\000\012\006\uffc5\014" +
    "\uffc5\032\uffc5\033\uffc5\001\002\000\012\006\uffc8\014\uffc8" +
    "\032\070\033\uffc8\001\002\000\036\006\uffd6\012\uffd6\014" +
    "\uffd6\016\uffd6\017\uffd6\020\104\021\105\032\uffd6\033\uffd6" +
    "\034\uffd6\035\uffd6\036\uffd6\037\uffd6\040\uffd6\001\002\000" +
    "\012\011\057\043\052\044\047\050\051\001\002\000\020" +
    "\016\100\017\075\034\076\035\073\036\101\037\077\040" +
    "\102\001\002\000\012\011\057\043\052\044\047\050\051" +
    "\001\002\000\006\006\064\033\063\001\002\000\014\011" +
    "\057\031\061\043\052\044\047\050\051\001\002\000\004" +
    "\007\uffe2\001\002\000\004\007\030\001\002\000\032\004" +
    "\uffe1\007\uffe1\010\uffe1\014\uffe1\022\uffe1\025\uffe1\026\uffe1" +
    "\027\uffe1\045\uffe1\046\uffe1\047\uffe1\050\uffe1\001\002\000" +
    "\012\006\uffc9\014\uffc9\032\070\033\uffc9\001\002\000\014" +
    "\011\057\031\061\043\052\044\047\050\051\001\002\000" +
    "\012\006\uffc7\014\uffc7\032\uffc7\033\uffc7\001\002\000\012" +
    "\006\uffc4\014\uffc4\032\uffc4\033\uffc4\001\002\000\012\011" +
    "\uffc1\043\uffc1\044\uffc1\050\uffc1\001\002\000\012\011\057" +
    "\043\052\044\047\050\051\001\002\000\012\011\057\043" +
    "\052\044\047\050\051\001\002\000\012\011\uffc2\043\uffc2" +
    "\044\uffc2\050\uffc2\001\002\000\012\011\uffbe\043\uffbe\044" +
    "\uffbe\050\uffbe\001\002\000\012\011\057\043\052\044\047" +
    "\050\051\001\002\000\012\011\uffc0\043\uffc0\044\uffc0\050" +
    "\uffc0\001\002\000\012\011\uffbf\043\uffbf\044\uffbf\050\uffbf" +
    "\001\002\000\036\006\uffd8\012\uffd8\014\uffd8\016\uffd8\017" +
    "\uffd8\020\104\021\105\032\uffd8\033\uffd8\034\uffd8\035\uffd8" +
    "\036\uffd8\037\uffd8\040\uffd8\001\002\000\012\011\057\043" +
    "\052\044\047\050\051\001\002\000\012\011\057\043\052" +
    "\044\047\050\051\001\002\000\036\006\uffd4\012\uffd4\014" +
    "\uffd4\016\uffd4\017\uffd4\020\uffd4\021\uffd4\032\uffd4\033\uffd4" +
    "\034\uffd4\035\uffd4\036\uffd4\037\uffd4\040\uffd4\001\002\000" +
    "\036\006\uffd5\012\uffd5\014\uffd5\016\uffd5\017\uffd5\020\uffd5" +
    "\021\uffd5\032\uffd5\033\uffd5\034\uffd5\035\uffd5\036\uffd5\037" +
    "\uffd5\040\uffd5\001\002\000\036\006\uffd7\012\uffd7\014\uffd7" +
    "\016\uffd7\017\uffd7\020\104\021\105\032\uffd7\033\uffd7\034" +
    "\uffd7\035\uffd7\036\uffd7\037\uffd7\040\uffd7\001\002\000\016" +
    "\006\uffc3\014\uffc3\016\100\017\075\032\uffc3\033\uffc3\001" +
    "\002\000\010\012\uffd1\016\100\017\075\001\002\000\004" +
    "\012\114\001\002\000\036\006\uffd0\012\uffd0\014\uffd0\016" +
    "\uffd0\017\uffd0\020\uffd0\021\uffd0\032\uffd0\033\uffd0\034\uffd0" +
    "\035\uffd0\036\uffd0\037\uffd0\040\uffd0\001\002\000\006\006" +
    "\uffd9\050\117\001\002\000\004\006\122\001\002\000\010" +
    "\006\uffdb\013\120\014\uffdb\001\002\000\010\006\uffd9\014" +
    "\uffd9\050\117\001\002\000\006\006\uffda\014\uffda\001\002" +
    "\000\036\006\uffd2\012\uffd2\014\uffd2\016\uffd2\017\uffd2\020" +
    "\uffd2\021\uffd2\032\uffd2\033\uffd2\034\uffd2\035\uffd2\036\uffd2" +
    "\037\uffd2\040\uffd2\001\002\000\010\014\124\016\100\017" +
    "\075\001\002\000\032\004\uffea\007\uffea\010\uffea\014\uffea" +
    "\022\uffea\025\uffea\026\uffea\027\uffea\045\uffea\046\uffea\047" +
    "\uffea\050\uffea\001\002\000\004\007\030\001\002\000\004" +
    "\030\127\001\002\000\004\005\130\001\002\000\014\011" +
    "\057\031\061\043\052\044\047\050\051\001\002\000\006" +
    "\006\132\033\063\001\002\000\032\004\uffdf\007\uffdf\010" +
    "\uffdf\014\uffdf\022\uffdf\025\uffdf\026\uffdf\027\uffdf\045\uffdf" +
    "\046\uffdf\047\uffdf\050\uffdf\001\002\000\004\014\uffee\001" +
    "\002\000\004\014\135\001\002\000\032\004\uffed\007\uffed" +
    "\010\uffed\014\uffed\022\uffed\025\uffed\026\uffed\027\uffed\045" +
    "\uffed\046\uffed\047\uffed\050\uffed\001\002\000\032\004\ufff0" +
    "\007\ufff0\010\ufff0\014\ufff0\022\ufff0\025\ufff0\026\ufff0\027" +
    "\ufff0\045\ufff0\046\ufff0\047\ufff0\050\ufff0\001\002\000\042" +
    "\002\ufff1\004\ufff1\007\ufff1\010\ufff1\014\ufff1\022\ufff1\024" +
    "\ufff1\025\ufff1\026\ufff1\027\ufff1\030\ufff1\041\ufff1\045\ufff1" +
    "\046\ufff1\047\ufff1\050\ufff1\001\002\000\012\011\057\043" +
    "\052\044\047\050\051\001\002\000\006\006\uffd9\050\117" +
    "\001\002\000\004\006\143\001\002\000\004\014\144\001" +
    "\002\000\032\004\uffeb\007\uffeb\010\uffeb\014\uffeb\022\uffeb" +
    "\025\uffeb\026\uffeb\027\uffeb\045\uffeb\046\uffeb\047\uffeb\050" +
    "\uffeb\001\002\000\010\014\146\016\100\017\075\001\002" +
    "\000\032\004\uffec\007\uffec\010\uffec\014\uffec\022\uffec\025" +
    "\uffec\026\uffec\027\uffec\045\uffec\046\uffec\047\uffec\050\uffec" +
    "\001\002\000\004\050\150\001\002\000\004\015\151\001" +
    "\002\000\012\011\057\043\052\044\047\050\051\001\002" +
    "\000\010\014\153\016\100\017\075\001\002\000\014\011" +
    "\057\031\061\043\052\044\047\050\051\001\002\000\006" +
    "\014\155\033\063\001\002\000\004\050\156\001\002\000" +
    "\004\015\157\001\002\000\012\011\057\043\052\044\047" +
    "\050\051\001\002\000\010\006\161\016\100\017\075\001" +
    "\002\000\004\007\uffe4\001\002\000\004\007\030\001\002" +
    "\000\032\004\uffe3\007\uffe3\010\uffe3\014\uffe3\022\uffe3\025" +
    "\uffe3\026\uffe3\027\uffe3\045\uffe3\046\uffe3\047\uffe3\050\uffe3" +
    "\001\002\000\014\011\057\031\061\043\052\044\047\050" +
    "\051\001\002\000\006\006\166\033\063\001\002\000\004" +
    "\023\167\001\002\000\004\007\uffe9\001\002\000\004\007" +
    "\030\001\002\000\034\004\uffe5\007\uffe5\010\uffe5\014\uffe5" +
    "\022\uffe5\024\172\025\uffe5\026\uffe5\027\uffe5\045\uffe5\046" +
    "\uffe5\047\uffe5\050\uffe5\001\002\000\004\007\uffe7\001\002" +
    "\000\032\004\uffe8\007\uffe8\010\uffe8\014\uffe8\022\uffe8\025" +
    "\uffe8\026\uffe8\027\uffe8\045\uffe8\046\uffe8\047\uffe8\050\uffe8" +
    "\001\002\000\004\007\030\001\002\000\032\004\uffe6\007" +
    "\uffe6\010\uffe6\014\uffe6\022\uffe6\025\uffe6\026\uffe6\027\uffe6" +
    "\045\uffe6\046\uffe6\047\uffe6\050\uffe6\001\002\000\010\045" +
    "\011\046\010\047\014\001\002\000\004\006\200\001\002" +
    "\000\004\007\030\001\002\000\014\002\ufff7\041\ufff7\045" +
    "\ufff7\046\ufff7\047\ufff7\001\002\000\004\050\203\001\002" +
    "\000\006\006\ufff4\013\ufff4\001\002\000\010\045\ufffc\046" +
    "\ufffc\047\ufffc\001\002\000\004\014\206\001\002\000\012" +
    "\041\ufffa\045\ufffa\046\ufffa\047\ufffa\001\002\000\004\002" +
    "\ufffe\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\206\000\014\002\012\003\006\004\003\005\004\014" +
    "\011\001\001\000\002\001\001\000\014\002\012\003\006" +
    "\004\206\005\004\014\011\001\001\000\002\001\001\000" +
    "\006\002\203\003\006\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\017\016\001\001\000\006\005\014\014" +
    "\011\001\001\000\002\001\001\000\014\002\012\003\006" +
    "\004\015\005\004\014\011\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\014\023\016\021" +
    "\001\001\000\004\026\176\001\001\000\004\027\025\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\006\030\001\001\000\012\007\035\010\036\014" +
    "\037\036\043\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\010\135\014\037\036\043\001\001\000\002\001\001" +
    "\000\004\015\132\001\001\000\004\035\124\001\001\000" +
    "\010\011\122\012\055\013\052\001\001\000\002\001\001" +
    "\000\004\006\044\001\001\000\002\001\001\000\020\011" +
    "\057\012\055\013\052\020\061\021\054\022\047\023\053" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\011\111\012" +
    "\055\013\052\001\001\000\004\024\073\001\001\000\012" +
    "\011\057\012\055\013\052\023\071\001\001\000\002\001" +
    "\001\000\016\011\057\012\055\013\052\021\066\022\047" +
    "\023\053\001\001\000\004\034\064\001\001\000\004\006" +
    "\065\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\011\057\012\055\013\052\022\070\023\053\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\011\110\012\055\013\052\001\001\000\006\012\107\013" +
    "\052\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\012\102\013\052\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\013\106\001\001\000\004" +
    "\013\105\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\037\112\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\015\115\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\015\120" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\125\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\011\057\012\055\013" +
    "\052\020\130\021\054\022\047\023\053\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\030\133\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\011\144\012\055\013\052\001\001\000" +
    "\004\015\141\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\011\151\012\055" +
    "\013\052\001\001\000\002\001\001\000\020\011\057\012" +
    "\055\013\052\020\153\021\054\022\047\023\053\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\011\157\012\055\013\052\001\001\000\002\001\001" +
    "\000\004\033\161\001\001\000\004\006\162\001\001\000" +
    "\002\001\001\000\020\011\057\012\055\013\052\020\164" +
    "\021\054\022\047\023\053\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\031\167\001\001\000\004\006\170" +
    "\001\001\000\004\025\172\001\001\000\004\032\173\001" +
    "\001\000\002\001\001\000\004\006\174\001\001\000\002" +
    "\001\001\000\004\014\201\001\001\000\002\001\001\000" +
    "\004\006\200\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




	private Ambito root;
	private Ambito actual;

	/* Es un metodo que el cual se llama automaticamente al haber un error en la gramatica, 
	con el que informamos de la linea y la columna en el que se encuentra dicho error.*/
	
	@Override 
	public void syntax_error(Symbol s) { 
		int l = s.left + 1;
		int c = s.right + 1;
		report_error("El String: '" + s.value + "' ha producido un error en la linea " + l + ", columna " + c + ".\n", null);
	}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {


	
	private Ambito root = new Ambito();
	private Ambito actual = this.root;
	private Function function = null;
	
		
	private void idNotExist(String id, int line) {
		System.out.println("Line: " + line + " El identificador \"" + id + "\" no existe.");
	}

	private Type getTypeOperation(Operador op, Type type1, Type type2, int line) {		
		Type type = new Type();
		
		if (type1.isError() || type2.isError()) {
			return type;
		}
		
		if (type1.equals(type2)) {
			type = type1;
		} else {
			System.err.println("Line: " + line + " Incompatible types " + type1.toString() + " " + op.toString() + " " + type2.toString());			
		}
		return type;	
	}
	
	private Type getTypeCallFunction(String id, Lid lid, int line) {
		Function func = null;
		Command cmd = null;
		Type type = new Type();
			
		cmd = this.actual.buscar(id);
		if (cmd == null && !(cmd instanceof Function)) {
			System.err.println("Line:" + line + " La funcion \"" + id + "\" no existe");
		} else {
			func = (Function) cmd;
			type = cmd.getTipo();
		}
		
		if (func != null && !type.isError()) {
			TupleTypes idTypes_1 = func.getListParamsTypes();
			TupleTypes idTypes_2 = this.actual.buscaIdsType(lid);
			
			boolean success = idTypes_1.compare(idTypes_2);
			if (!success) {
				func.usage(idTypes_1, idTypes_2, line);
				type.setError();
			}
		}
		return type;		
	}		
	
	private Type getAssignType(String id, Type exp, int line) {
		Command cmd = this.actual.buscar(id);
		Type type = new Type();
		
		if (cmd != null && !exp.isError()) {
			Operador op = new Operador("=");
			type = getTypeOperation(op, cmd.tipo(), exp,  line);			
		}  else if (cmd == null) {
			idNotExist(id, line);
		}
		return type;
	}	


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // PROGRAM ::= INCLUDE PART PROGRAM 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PROGRAM",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= PROGRAM EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // PROGRAM ::= INCLUDE PART 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PROGRAM",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // PROGRAM ::= PART PROGRAM 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PROGRAM",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // PROGRAM ::= PART 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PROGRAM",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INCLUDE ::= FILE INCLUDE 
            {
              Include RESULT =null;
		int fileleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int fileright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		File file = (File)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	Include include = new Include(file);
	include.include(this.root);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("INCLUDE",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INCLUDE ::= FILE 
            {
              Include RESULT =null;
		int fileleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fileright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		File file = (File)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			
	Include include = new Include(file);
	include.include(this.root);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("INCLUDE",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // FILE ::= include hfile semicolon 
            {
              File RESULT =null;
		int fileleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int fileright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String file = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	RESULT = new File(file);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FILE",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // PART ::= TYPE RESTPART 
            {
              Object RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int commandleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int commandright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Command command = (Command)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 			
	if (function != null) {
		function.insertarTipo(type);		
		function.checkReturnType(type, typeleft + 1);
	}
	this.actual = this.root;
	function = null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PART",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$0 ::= 
            {
              Command RESULT =null;
		int idLexemaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idLexemaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String idLexema = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ListParams list = (ListParams)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

	function = this.root.insertarFuncion(idLexema);
		
	if (function != null) {
		this.actual = function.getAmbito();
		function.insertarParametros(list, listleft + 1);
	}
	

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // RESTPART ::= tid l_par LISTPARAM NT$0 r_par BLQ 
            {
              Command RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Command) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idLexemaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idLexemaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String idLexema = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ListParams list = (ListParams)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int typesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typesright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TupleTypes types = (TupleTypes)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	if (function != null) {
		function.insertReturnTypes(types);
	}	

              CUP$parser$result = parser.getSymbolFactory().newSymbol("RESTPART",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$1 ::= 
            {
              Command RESULT =null;
		int idLexemaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idLexemaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String idLexema = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

	function = this.root.insertarFuncion(idLexema);
	
	if (function != null) {
		this.actual = function.getAmbito();
	}
	

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // RESTPART ::= tid l_par tvoid NT$1 r_par BLQ 
            {
              Command RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Command) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idLexemaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idLexemaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String idLexema = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int typesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typesright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TupleTypes types = (TupleTypes)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	if (function != null) {
		function.insertReturnTypes(types);
	}

              CUP$parser$result = parser.getSymbolFactory().newSymbol("RESTPART",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // LISTPARAM ::= LISTPARAM comma TYPE tid 
            {
              ListParams RESULT =null;
		int listparamsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int listparamsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ListParams listparams = (ListParams)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
	listparams.insertar(new Parametro(id, type));
	RESULT = listparams;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTPARAM",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // LISTPARAM ::= TYPE tid 
            {
              ListParams RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
	ListParams listparams = new ListParams();

	listparams.insertar(new Parametro(id, type));
	RESULT = listparams;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTPARAM",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // LISTPARAM ::= 
            {
              ListParams RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTPARAM",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // BLQ ::= l_brace SENTLIST r_brace 
            {
              TupleTypes RESULT =null;
		int typesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TupleTypes types = (TupleTypes)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 	
	if (this.actual.getFather() != null) {
		this.actual = this.actual.getFather();
	} else {
		this.actual = this.root;
	}
	RESULT = types;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BLQ",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // SENTLIST ::= SENTLIST SENT 
            {
              TupleTypes RESULT =null;
		int typesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TupleTypes types = (TupleTypes)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	types.insert(type);
	RESULT = types;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTLIST",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // SENTLIST ::= SENT 
            {
              TupleTypes RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	TupleTypes types = new TupleTypes();
	types.insert(type);
	RESULT = types;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENTLIST",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // NT$2 ::= 
            {
              Type RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int lidleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lidright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Lid lid = (Lid)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 
	for(String id : lid.getList()) {
		this.actual.insertaIdVariable(new Variable(id, type));
	}	

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // SENT ::= TYPE LID NT$2 semicolon 
            {
              Type RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Type) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int lidleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lidright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Lid lid = (Lid)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENT",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // SENT ::= tid assig EXP semicolon 
            {
              Type RESULT =null;
		int idLexemaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idLexemaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String idLexema = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int typeExpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeExpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Type typeExp = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
	RESULT = getAssignType(idLexema, typeExp, idLexemaleft + 1);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENT",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // SENT ::= tid l_par LID r_par semicolon 
            {
              Type RESULT =null;
		int idLexemaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idLexemaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String idLexema = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int lidleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lidright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Lid lid = (Lid)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 
	Type type = new Type();

	if (!getTypeCallFunction(idLexema, lid, lidleft + 1).isError()) {
		type.setVoid();
	}
	RESULT = type;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENT",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // SENT ::= treturn EXP semicolon 
            {
              Type RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	type.setReturn();
	RESULT = type;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENT",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // NT$3 ::= 
            {
              Type RESULT =null;


	this.actual = new Ambito(this.actual);
	

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // SENT ::= tif l_par LCOND r_par tthen NT$3 BLQ IF2 
            {
              Type RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Type) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENT",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // NT$4 ::= 
            {
              Object RESULT =null;
 

	this.actual = new Ambito(this.actual);


              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$4",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // IF2 ::= telse NT$4 BLQ 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IF2",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // IF2 ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IF2",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // NT$5 ::= 
            {
              Type RESULT =null;
		int idLexema1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left;
		int idLexema1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).right;
		String idLexema1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;
		int exp1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		Type exp1 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int idLexema2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idLexema2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String idLexema2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Type exp2 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

	Type type1 = getAssignType(idLexema1, exp1, idLexema1left + 1);
	Type type2 = getAssignType(idLexema2, exp2, idLexema2left + 1);	
	
	if (type1.isError() || type2.isError()) {
		RESULT = new Type();
	}
	RESULT = type1; // El tipo del for lo damos como el de la variable de incialización...

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$5",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // SENT ::= tfor l_par tid assig EXP semicolon LCOND semicolon tid assig EXP r_par NT$5 BLQ 
            {
              Type RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Type) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idLexema1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)).left;
		int idLexema1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)).right;
		String idLexema1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-11)).value;
		int exp1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).right;
		Type exp1 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;
		int idLexema2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idLexema2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String idLexema2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Type exp2 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENT",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-13)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // NT$6 ::= 
            {
              Type RESULT =null;


	this.actual = new Ambito(this.actual);


              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$6",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // SENT ::= twhile l_par LCOND r_par NT$6 BLQ 
            {
              Type RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Type) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENT",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // NT$7 ::= 
            {
              Type RESULT =null;


	this.actual = new Ambito(this.actual);


              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$7",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // SENT ::= tdo NT$7 BLQ tuntil l_par LCOND r_par 
            {
              Type RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Type) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENT",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // NT$8 ::= 
            {
              Type RESULT =null;


	this.actual = new Ambito(this.actual);


              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$8",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // SENT ::= NT$8 BLQ 
            {
              Type RESULT =null;
              // propagate RESULT from NT$8
                RESULT = (Type) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENT",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // SENT ::= semicolon 
            {
              Type RESULT =null;
		
	;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SENT",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // LID ::= tid 
            {
              Lid RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 

	Lid lid = new Lid();
	lid.add(id);
	RESULT = lid; 


              CUP$parser$result = parser.getSymbolFactory().newSymbol("LID",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // LID ::= tid comma LID 
            {
              Lid RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int lidleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lidright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Lid lid = (Lid)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		

	lid.add(id);
	RESULT = lid; 	


              CUP$parser$result = parser.getSymbolFactory().newSymbol("LID",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // LID ::= 
            {
              Lid RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LID",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // EXP ::= EXP add EXPT 
            {
              Type RESULT =null;
		int type1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int type1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Type type1 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int type2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int type2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type type2 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	Operador op = new Operador(" + ");

	RESULT = getTypeOperation(op, type1, type2, type1left + 1);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // EXP ::= EXP sub EXPT 
            {
              Type RESULT =null;
		int type1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int type1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Type type1 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int type2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int type2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type type2 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	Operador op = new Operador(" - ");

	RESULT = getTypeOperation(op, type1, type2, type1left + 1);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // EXP ::= EXPT 
            {
              Type RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			
	RESULT = type;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // EXPT ::= EXPT mul FACTOR 
            {
              Type RESULT =null;
		int type1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int type1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Type type1 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int type2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int type2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type type2 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	Operador op = new Operador(" x ");

	RESULT = getTypeOperation(op, type1, type2, type1left + 1);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPT",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // EXPT ::= EXPT div FACTOR 
            {
              Type RESULT =null;
		int type1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int type1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Type type1 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int type2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int type2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type type2 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	Operador op = new Operador(" / ");
	
	RESULT = getTypeOperation(op, type1, type2, type1left + 1);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPT",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // EXPT ::= FACTOR 
            {
              Type RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			
	RESULT = type;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPT",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // FACTOR ::= tid l_par LID r_par 
            {
              Type RESULT =null;
		int idLexemaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idLexemaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String idLexema = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int lidleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lidright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Lid lid = (Lid)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	RESULT = getTypeCallFunction(idLexema, lid, lidleft + 1);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FACTOR",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // NT$9 ::= 
            {
              Type RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

	RESULT = type;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$9",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // FACTOR ::= l_bracket EXP NT$9 r_bracket 
            {
              Type RESULT =null;
              // propagate RESULT from NT$9
                RESULT = (Type) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FACTOR",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // FACTOR ::= tid 
            {
              Type RESULT =null;
		int idLexemaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idLexemaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String idLexema = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	Type type = new Type();
	Command cmd = this.actual.buscar(idLexema);	

	if (cmd == null) {
		idNotExist(idLexema, (idLexemaleft + 1));
	} else {
		type = cmd.tipo();
	}
	RESULT = type;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FACTOR",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // FACTOR ::= constint 
            {
              Type RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	RESULT = new Type(EnumType.INT, vleft);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FACTOR",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // FACTOR ::= constfloat 
            {
              Type RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	RESULT = new Type(EnumType.FLOAT, vleft);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FACTOR",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // TYPE ::= tvoid 
            {
              Type RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  new Type(EnumType.VOID, vleft); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TYPE",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // TYPE ::= tint 
            {
              Type RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  new Type(EnumType.INT, ileft); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TYPE",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // TYPE ::= tfloat 
            {
              Type RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  new Type(EnumType.FLOAT, fleft); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TYPE",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // LCOND ::= LCOND tor LCONDT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LCOND",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // LCOND ::= LCONDT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LCOND",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // LCONDT ::= LCONDT tand LCONDF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LCONDT",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // LCONDT ::= LCONDF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LCONDT",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // LCONDF ::= COND 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LCONDF",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // LCONDF ::= tnot COND 
            {
              Object RESULT =null;
		
	;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LCONDF",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // COND ::= EXP OPR EXP 
            {
              Object RESULT =null;
		int type1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int type1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Type type1 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Operador op = (Operador)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int type2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int type2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type type2 = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	RESULT = getTypeOperation(op, type1, type2, type1left + 1);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COND",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // OPR ::= equals 
            {
              Operador RESULT =null;
		
	RESULT = new Operador(" == ");

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // OPR ::= less 
            {
              Operador RESULT =null;
		
	RESULT = new Operador(" < ");

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // OPR ::= greater 
            {
              Operador RESULT =null;
		
	RESULT = new Operador(" > ");

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // OPR ::= greaterequal 
            {
              Operador RESULT =null;
		
	RESULT = new Operador(" >= ");

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // OPR ::= lessequal 
            {
              Operador RESULT =null;
		
	RESULT = new Operador(" <= ");

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
